---
- hosts: all
  vars_files:
    - vars/main.yml
  handlers:
    - import_tasks: handlers/main.yml
  tasks:
    - include_tasks: tasks/install_with_dnf.yml
    - include_tasks: tasks/edit_filesystem.yml
    - include_tasks: tasks/install_sublime.yml
    - include_tasks: tasks/install_aws_cli.yml
    - include_tasks: tasks/install_vscode.yml
    - include_tasks: tasks/edit_bashrc.yml
    - include_tasks: tasks/install_with_snapd.yml
