---
- name: Populate aliases for .bashrc
  block:
    # NOTE: We only need to check this because the newline is not idempotent for some reason.
    - name: Checking if aliases comment exists
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        search_string: "# aliases"
        state: absent
      check_mode: yes
      changed_when: false
      register: exists

    - name: Adding aliases comment for neatness
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        line: "\n# aliases"
      when: not exists.found

    - name: Adding aliases
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        line: "alias {{ item.key }}='{{ item.value }}'"
      loop: "{{ aliases | dict2items }}"

- name: Add extra paths to PATH variable
  block:
    - name: Checking if path comment exists
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        search_string: "# paths"
        state: absent
      check_mode: yes
      changed_when: false
      register: exists

    - name: Adding paths comment for neatness
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        line: "\n# paths"
      when: not exists.found

    - name: Adding paths
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        line: "export PATH=$PATH:{{ item }}"
      loop: "{{ extra_paths }}"
