---
- name: Update via dnf
  become: yes
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install packages via dnf
  become: yes
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ dnf_packages }}"
  notify: Start snapd.socket

- ansible.builtin.meta: flush_handlers

