---
- name: Starting snapd.socket in systemd
  become: true
  ansible.builtin.systemd:
    name: snapd.socket
    state: started
    enabled: yes
  listen: Start snapd.socket
  notify:
    - Start snapd

- name: Starting snapd in systemd
  become: true
  ansible.builtin.systemd:
    name: snapd
    state: started
    enabled: yes
  listen: Start snapd
